# Generated by Django 5.0.10 on 2025-01-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_rename_workout_session_name_workoutsession_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="set",
            options={"ordering": ("set_number",)},
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="date",
            new_name="workout_date",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="name",
            new_name="workout_name",
        ),
    ]
