# Generated by Django 5.0.10 on 2025-01-03 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "muscles_worked",
                    models.CharField(
                        choices=[
                            ("CH", "Chest"),
                            ("BK", "Back"),
                            ("LG", "Legs"),
                            ("AB", "Abs"),
                            ("SH", "Shoulders"),
                            ("AR", "Arms"),
                        ],
                        max_length=2,
                    ),
                ),
                ("exercise_name", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
