# Generated by Django 5.0.10 on 2025-01-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_workout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Workout",
        ),
    ]
